name: Dotnet 7 Web API Unit Tests

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: |
        export MONGO_DB_ENV="ci-cd" &&
        dotnet test


